numbers = [5, 2, 1, 5, 7, 4, 20]
numbers.insert(0, 10)
numbers.remove(5)
numbers.clear()
# numbers.pop()
print(numbers)
# print(numbers.index(5))
print(50 in numbers)
print(numbers.count(5))
print(numbers.sort())
numbers.sort()
numbers.reverse()
numbers2 = numbers.copy()
numbers.append(10)
